In [1]:
import pandas as pd
import numpy as np

In [2]:
data_xls = pd.read_excel(r'C:\Users\Hp\Downloads\ExtractedFeatures_Plus_subsetData.xlsx', index_col=None)
data_xls.to_csv('csvfile.csv', encoding='utf-8', index = False)
# r before path is to ensure its regarded as a raw string and not like any other string

In [3]:
data_xls.head()

Mean_x    Mean_y    Mean_z  Median_x  Median_y  Median_z     Min_x  \
0 -0.423737  0.021819 -0.330184 -0.444600  0.020301 -0.334125 -1.215443   
1 -0.087148 -0.462259 -0.096391 -0.097399 -0.462144 -0.095909 -0.299703   
2  0.024604 -0.440365 -0.088574  0.015755 -0.447316 -0.095221 -0.278861   
3 -0.054298 -0.495041 -0.215878 -0.060291 -0.495915 -0.218912 -0.239450   
4  0.056221 -0.517619  0.381889  0.051731 -0.521420  0.383361 -0.088581   

      Min_y     Min_z     Max_x  ...  Right leg bone mass  \
0 -0.716660 -1.040794  0.405263  ...                  606   
1 -0.816102 -0.271787  0.205384  ...                  479   
2 -0.940211 -0.462715  0.495626  ...                  527   
3 -0.804632 -0.442392  0.201034  ...                  381   
4 -0.711505  0.211637  0.258780  ...                  352   

   Left leg total mass (kg)  Left leg tissue mass  Left leg fat free mass  \
0                      11.6                 10984                    8582   
1                      11.9                 11443                    7365   
2                      10.0                  9524                    8833   
3                      11.0                 10563                    6802   
4                      10.9                 10568                    6499   

   Left leg lean mass  Left leg fat mass  Left leg bone mass  \
0                7986               2998                 595   
1                6907               4537                 459   
2                8318               1206                 515   
3                6398               4165                 404   
4                6159               4409                 340   

   sway trace length  falls previous  falls after study combined  
0               1583               0                           0  
1                388               0                           0  
2               1671               0                           0  
3                370               0                           0  
4                306               1                           1  

[5 rows x 59 columns]

In [4]:
X = data_xls.iloc[:, :-1].values
y = data_xls.iloc[:, -1].values

In [5]:
print("Independent variables : ")
print(X)
print("Target variable : ")
print(y)

Independent variables : 
[[-4.23736925e-01  2.18192949e-02 -3.30183677e-01 ...  5.95000000e+02
   1.58300000e+03  0.00000000e+00]
 [-8.71484343e-02 -4.62258950e-01 -9.63913009e-02 ...  4.59000000e+02
   3.88000000e+02  0.00000000e+00]
 [ 2.46042365e-02 -4.40365365e-01 -8.85742832e-02 ...  5.15000000e+02
   1.67100000e+03  0.00000000e+00]
 ...
 [-1.87395348e-01 -3.92346429e-01 -1.28873773e-01 ...  5.41000000e+02
   2.34000000e+02  0.00000000e+00]
 [-2.44790616e-02 -5.52402784e-01 -1.88995025e-01 ...  5.94000000e+02
   4.77000000e+02  1.00000000e+00]
 [-6.13786014e-02 -4.56816990e-01  1.57993122e-01 ...  4.19000000e+02
   2.72000000e+02  0.00000000e+00]]
Target variable : 
[0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 0 1
 1 1 1 1 0 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 1]


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.svm import SVC

classifier = SVC(kernel = "linear")
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_auc_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[12  6]
 [ 3  9]]
              precision    recall  f1-score   support

           0       0.80      0.67      0.73        18
           1       0.60      0.75      0.67        12

    accuracy                           0.70        30
   macro avg       0.70      0.71      0.70        30
weighted avg       0.72      0.70      0.70        30

0.7
0.7083333333333334


In [10]:
print(y_pred)
print(y_test)

[0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0]
[0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1]
